---
language: python
sudo: required
services:
  - docker
install: pip install tox
script: sed -i "s/MARATHON_VERSION/${MARATHON_VERSION}/g" docker-compose.yml && tox
env:
  - MARATHON_VERSION: latest-dev
  - MARATHON_VERSION: latest
  - MARATHON_VERSION: v1.4.3
