zookeeper:
  build: dockerfiles/zookeeper/
  ports:
    - 2181
mesosmaster:
  build: dockerfiles/mesos/
  ports:
    - 5050
  links:
    - zookeeper
  command: 'mesos-master --zk=zk://zookeeper:2181/mesos-testcluster --registry=in_memory --quorum=1 --authenticate --authenticate_slaves --credentials=/etc/mesos-secrets'

mesosslave:
  build: dockerfiles/mesos/
  ports:
    - 5051
  links:
    - zookeeper
  environment:
    -CLUSTER: testcluster
  command: 'mesos-slave --master=zk://zookeeper:2181/mesos-testcluster --resources="cpus(*):10; mem(*):512; disk(*):100" --credential=/etc/mesos-slave-secret --containerizers=docker --docker=/usr/bin/docker --attributes="region:fakeregion;pool:default"'
  hostname: mesosslave.test_hostname
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock

marathon:
  build: dockerfiles/marathon/
  ports:
    - 8080
  links:
    - zookeeper
  environment:
    -CLUSTER: testcluster
  command: 'marathon --zk zk://zookeeper:2181/marathon --master zk://zookeeper:2181/mesos-testcluster --no-logger --env_vars_prefix MARATHON_ --mesos_authentication_principal marathon --mesos_authentication_secret_file /etc/marathon_framework_secret'

behave:
  build: dockerfiles/behave/
  links:
    - marathon
    - mesosmaster
    - mesosslave
    - zookeeper
  volumes:
  - ./:/work:rw

